<?php
// Variables
return [
  'creatorName' => 'Semangkamedia',
  'creatorUrl' => 'https://abukafa.github.io',
  'ourWebsite' => 'https://info.jazacademy.id',
  'templateName' => 'Jazmedia',
  'templateSuffix' => 'Project Management System',
  'templateVersion' => '1.0.0',
  'templateFree' => false,
  'templateDescription' => 'Start your project management right here!',
  'templateKeyword' => 'school, project, managemen',
  'licenseUrl' => '',
  'livePreview' => '',
  'productPage' => '',
  'support' => 'http://semangkamedia.epizy.com/',
  'moreThemes' => '',
  'documentation' => 'https://demos.pixinvent.com/vuexy-vuejs-admin-template/documentation/',
  'generator' => '',
  'changelog' => '',
  'repository' => '',
  'gitRepo' => '',
  'gitRepoAccess' => '',
  'githubFreeUrl' => 'https://github.com/jaz-academy',
  'facebookUrl' => 'https://www.facebook.com//',
  'twitterUrl' => 'https://twitter.com/',
  'githubUrl' => 'https://github.com/jaz-academy',
  'dribbbleUrl' => 'https://dribbble.com/',
  'instagramUrl' => 'https://www.instagram.com/jazacademy.id/',
  'whatsapp' => 'https://wa.me/+6281222299964',
];
